version: '3.8'

services:
  cursos-service:
    build:
      context: ./cursos
      dockerfile: Dockerfile
    container_name: cursos-service
    ports:
      - "8080:8080"
    depends_on:
      - cursos-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cursos-db:5432/cursosdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - ESTUDIANTES_SERVICE_URL=http://estudiantes-service:8080

  estudiantes-service:
    build:
      context: ./estudiantes
      dockerfile: Dockerfile
    container_name: estudiantes-service
    ports:
      - "8081:8080"
    depends_on:
      - estudiantes-db
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://estudiantes-db:5432/estudiantesdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - CURSOS_SERVICE_URL=http://cursos-service:8080

  cursos-db:
    image: postgres:13
    container_name: cursos-db
    environment:
      POSTGRES_DB: cursosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  estudiantes-db:
    image: postgres:13
    container_name: estudiantes-db
    environment:
      POSTGRES_DB: estudiantesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

